backend:
  image:
    repository: ghcr.io/ntth7419/yas-inventory
    tag: latest

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  service:
    type: NodePort
  ingress:
    enabled: true
    host: inventory.yas.local.com
