backend:
  image:
    repository: ngoctuan74/yas-rating
    tag: latest

  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  service:
    type: NodePort
    nodePort: 30014
  ingress:
    enabled: false
