backend:
  image:
    repository: ghcr.io/ntth7419/yas-rating
    tag: latest

  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  service:
    type: NodePort
  ingress:
    enabled: true
