apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-dev
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: cart
          - service: customer
          - service: inventory
          - service: media
          - service: order
          - service: product
          - service: search
          - service: tax
          - service: backoffice-bff
          - service: backoffice-ui
          - service: storefront-bff
          - service: swagger-ui
          - service: storefront-ui
  template:
    metadata:
      name: "{{service}}-dev"
      annotations:
        argocd-image-updater.argoproj.io/image-list: "backend=ngoctuan74/yas-{{service}}"
        argocd-image-updater.argoproj.io/backend.update-strategy: "digest"
        argocd-image-updater.argoproj.io/backend.allow-tags: "latest"
        argocd-image-updater.argoproj.io/backend.helm.image-name: "backend.image.repository"
        argocd-image-updater.argoproj.io/backend.helm.image-tag: "backend.image.tag"
        argocd-image-updater.argoproj.io/write-back-method: "argocd"
    spec:
      project: default
      source:
        repoURL: https://github.com/NTTH7419/yas-devops-2
        targetRevision: main
        path: "k8s/charts/{{service}}"
        helm:
          valueFiles:
            - "../../envs/dev/values-common.yaml"
            - "../../envs/dev/{{service}}.yaml"
          parameters:
            - name: "backend.image.tag"
              value: latest
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-staging
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-delete
  generators:
    - list:
        elements:
          - service: cart
          - service: customer
          - service: inventory
          - service: media
          - service: order
          - service: product
          - service: search
          - service: tax
          - service: backoffice-bff
          - service: backoffice-ui
          - service: storefront-bff
          - service: swagger-ui
          - service: storefront-ui
  template:
    metadata:
      name: "{{service}}-staging"
      annotations:
        argocd-image-updater.argoproj.io/image-list: "backend=ngoctuan74/yas-{{service}}"
        argocd-image-updater.argoproj.io/backend.update-strategy: "semver"
        argocd-image-updater.argoproj.io/backend.allow-tags: "regexp:^v[0-9]+\\.[0-9]+\\.[0-9]+$"
        argocd-image-updater.argoproj.io/backend.helm.image-name: "backend.image.repository"
        argocd-image-updater.argoproj.io/backend.helm.image-tag: "backend.image.tag"
        argocd-image-updater.argoproj.io/write-back-method: "argocd"
    spec:
      project: default
      source:
        repoURL: https://github.com/NTTH7419/yas-devops-2
        targetRevision: main
        path: "k8s/charts/{{service}}"
        helm:
          valueFiles:
            - "../../envs/staging/values-common.yaml"
            - "../../envs/staging/{{service}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
