backend:
  image:
    repository: ghcr.io/ntth7419/yas-product
    tag: latest

  nameOverride: product
  fullnameOverride: product
  databaseName: product
  service:
    type: NodePort
  ingress:
    enabled: true
    host: product.yas.local.com
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/yas/product
  extraApplicationConfigPaths:
    - /opt/yas/product/product-application.yaml  
