backend:
  image:
    repository: ngoctuan74/yas-promotion
    tag: latest

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  service:
    type: NodePort
    nodePort: 30013
  ingress:
    enabled: true
