backend:
  image:
    repository: ghcr.io/ntth7419/yas-promotion
    tag: latest

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  service:
    type: NodePort
  ingress:
    enabled: true
