ui:
  image:
    repository: ghcr.io/ntth7419/yas-backoffice
    tag: latest
  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  service:
    type: NodePort
  ingress:
    enabled: true
    host: backoffice.yas.local.com