backend:
  image:
    repository: ghcr.io/ntth7419/yas-location
    tag: latest

  nameOverride: location
  fullnameOverride: location
  databaseName: location
  service:
    type: NodePort
  ingress:
    enabled: true
