apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: annotation-image-updater
  namespace: argocd
spec:
  applicationRefs:
  - namePattern: "*-staging"
    useAnnotations: true
  - namePattern: "*-dev"
    useAnnotations: true
