  backend:
  image:
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    host: "api.dev.yas.local.com"
  service:
    type: NodePort
    nodePort: null
  podAnnotations:
    instrumentation.opentelemetry.io/inject-java: "true"

ui:
  service:
    type: NodePort
    nodePort: null
