backend:
  image:
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    host: "api.dev.yas.local.com"
  service:
    type: NodePort
    nodePort: null

ui:
  service:
    type: NodePort
    nodePort: null

mediaApplicationConfig:
  yas:
    publicUrl: http://api.dev.yas.local.com/media
