ui:
  service:
    type: NodePort
    nodePort: null
  ingress:
    enabled: false
    host: storefront.staging.yas.local.com

storefrontEnvProduction: |
  API_BASE_PATH=http://storefront.staging.yas.local.com/api
