apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: yas-instrumentation
  namespace: yas
spec:
  exporter:
    endpoint: http://opentelemetry-collector.observability:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.12.0
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dev-instrumentation
  namespace: dev
spec:
  exporter:
    endpoint: http://opentelemetry-collector.observability:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.12.0
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: staging-instrumentation
  namespace: staging
spec:
  exporter:
    endpoint: http://opentelemetry-collector.observability:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.12.0
