backend:
  image:
    repository: ghcr.io/ntth7419/yas-cart
    tag: latest

  nameOverride: cart
  fullnameOverride: cart
  databaseName: cart
  service:
    type: NodePort
  ingress:
    enabled: true
    host: cart.yas.local.com
  extraVolumes:
    - name: cart-application-config
      configMap:
        name: cart-application-configmap
  extraVolumeMounts:
    - name: cart-application-config
      mountPath: /opt/yas/cart
  extraApplicationConfigPaths:
    - /opt/yas/cart/cart-application.yaml
