backend:
  image:
    repository: ngoctuan74/yas-sampledata
    tag: latest

  nameOverride: sampledata
  fullnameOverride: sampledata
  databaseName: sampledata
  service:
    type: NodePort
    nodePort: 30022
  ingress:
    enabled: false
  extraVolumes:
    - name: sampledata-application
      configMap:
        name: sampledata-application-configmap
  extraVolumeMounts:
    - name: sampledata-application
      mountPath: /opt/yas/sampledata
  extraApplicationConfigPaths:
    - /opt/yas/sampledata/sampledata-application.yaml
