backend:
  image:
    repository: ngoctuan74/yas-tax
    tag: eed23b42

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  service:
    type: NodePort
    nodePort: 30019
  ingress:
    enabled: true
    host: tax.yas.local.com
