backend:
  image:
    repository: ngoctuan74/yas-tax
    tag: latest

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  service:
    type: NodePort
    nodePort: 30019
  ingress:
    enabled: false
