backend:
  image:
    repository: ghcr.io/ntth7419/yas-tax
    tag: eed23b42

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  service:
    type: NodePort
  ingress:
    enabled: true
    host: tax.yas.local.com
