name: backoffice service ci

on:
  push:
    branches: ["**"]
    paths:
      - "backoffice/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/backoffice-ci.yaml"
  pull_request:
    branches: ["**"]
    paths:
      - "backoffice/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/backoffice-ci.yaml"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: backoffice
      - run: npm run build
        working-directory: backoffice
      - run: npm run lint
        working-directory: backoffice
      - run: npx prettier --check .
        working-directory: backoffice
      - name: Snyk - Dependency Scan
        uses: snyk/actions/node@9adf32b1121593767fc3c057af55b55db032dc04
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=backoffice/package.json --severity-threshold=high
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: backoffice
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # - name: Log in to the Container registry
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build Docker image
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./backoffice
      #     push: false
      #     load: true
      #     tags: ghcr.io/nashtech-garage/yas-backoffice:latest
      # - name: Snyk - Container Scan
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: snyk/actions/docker@9adf32b1121593767fc3c057af55b55db032dc04
      #   continue-on-error: true
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     image: ghcr.io/nashtech-garage/yas-backoffice:latest
      #     args: --severity-threshold=high
      # - name: Push Docker image
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   run: docker push ghcr.io/nashtech-garage/yas-backoffice:latest
