name: cleanup_dev_deployment

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Uninstall Helm Releases
        run: |
          SERVICES=("backoffice-bff" "backoffice-ui" "cart" "customer" "inventory" "location" "media" "order" "payment" "payment-paypal" "product" "promotion" "rating" "recommendation" "sampledata" "search" "storefront-bff" "storefront-ui" "tax" "webhook")
          
          for SVC in "${SERVICES[@]}"; do
            if helm status $SVC -n yas > /dev/null 2>&1; then
              echo "Uninstalling $SVC..."
              helm uninstall $SVC -n yas
            fi
          done
          
          echo "Cleanup completed successfully."
