name: customer service ci

on:
  push:
    branches: ["**"]
    paths:
      - "customer/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/customer-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: ["**"]
    paths:
      - "customer/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/customer-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: ./.github/workflows/actions
      - name: Run Maven Verify (Test + Coverage)
        run: mvn verify -pl customer -am
      - name: Run Maven Checkstyle
        run: mvn checkstyle:checkstyle -pl customer -am -Dcheckstyle.output.file=customer-checkstyle-result.xml
      - name: Upload Checkstyle Result
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: "**/customer-checkstyle-result.xml"
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Snyk - Dependency Scan
        run: >
          snyk test
          --maven-aggregate-project
          --org=${{ vars.SNYK_ORG }}
          --severity-threshold=high
      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -pl customer -am
      - name: Test Results
        uses: dorny/test-reporter@v1
        if: ${{ success() || failure() }}
        with:
          name: Customer-Service-Unit-Test-Results
          path: "customer/**/*-reports/TEST*.xml"
          reporter: java-junit
      - name: Add coverage report to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{github.workspace}}/customer/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          title: "Customer Coverage Report"
          update-comment: true

  Build:
    needs: Test
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven Build Command
        run: mvn clean package -DskipTests -pl customer -am
      # - name: Log in to the Container registry
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build Docker image
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./customer
      #     push: false
      #     load: true
      #     tags: ghcr.io/nashtech-garage/yas-customer:latest
      # - name: Install Snyk CLI
      #   run: npm install -g snyk
      # - name: Snyk - Container Scan
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   continue-on-error: true
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   run: >
      #     snyk container test ghcr.io/nashtech-garage/yas-customer:latest 
      #     --file=customer/Dockerfile 
      #     --org=${{ vars.SNYK_ORG }}
      #     --project-name="yas/customer-container" 
      #     --severity-threshold=high
      # - name: Push Docker image
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   run: docker push ghcr.io/nashtech-garage/yas-customer:latest
