name: sampledata service ci

on:
  push:
    branches: ["**"]
    paths:
      - "sampledata/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/sampledata-ci.yaml"
      - "pom.xml"
      - ".snyk"
  pull_request:
    branches: ["**"]
    paths:
      - "sampledata/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/sampledata-ci.yaml"
      - "pom.xml"
      - ".snyk"
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: ./.github/workflows/actions
      - name: Run Maven Test Command
        run: mvn test -pl sampledata -am
      - name: Run Maven Checkstyle
        run: mvn checkstyle:checkstyle -pl sampledata -am -Dcheckstyle.output.file=sampledata-checkstyle-result.xml
      - name: Upload Checkstyle Result
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/sampledata-checkstyle-result.xml'

  Build:
    needs: Test
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: ./.github/workflows/actions
      - name: Run Maven Build Command
        run: mvn clean package -DskipTests -pl sampledata -am
      - name: Snyk - Dependency Scan
        run: >
          npx snyk test
          --maven-aggregate-project
          --org=${{ vars.SNYK_ORG }}
          --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Analyze with sonar cloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -pl sampledata -am
      # - name: Log in to the Container registry
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build Docker image
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./sampledata
      #     push: false
      #     load: true
      #     tags: ghcr.io/nashtech-garage/yas-sampledata:latest
      # - name: Install Snyk CLI
      #   run: npm install -g snyk
      # - name: Snyk - Container Scan
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   continue-on-error: true
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   run: >
      #     snyk container test ghcr.io/nashtech-garage/yas-sampledata:latest 
      #     --file=sampledata/Dockerfile 
      #     --org=ntth7419 
      #     --project-name="yas/sampledata-container" 
      #     --severity-threshold=high
      # - name: Push Docker image
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   run: docker push ghcr.io/nashtech-garage/yas-sampledata:latest

