name: tax service ci

on:
  push:
    branches: ["**"]
    paths:
      - "tax/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/tax-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: ["**"]
    paths:
      - "tax/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/tax-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: ./.github/workflows/actions
      - name: Run Maven Verify (Test + Coverage)
        run: mvn verify -pl tax -am
      - name: Run Maven Checkstyle
        run: mvn checkstyle:checkstyle -pl tax -am -Dcheckstyle.output.file=tax-checkstyle-result.xml
      - name: Upload Checkstyle Result
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/tax-checkstyle-result.xml'
      - name: Snyk - Dependency Scan
        uses: snyk/actions/maven@9adf32b1121593767fc3c057af55b55db032dc04
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -pl tax -am
      - name: Test Results
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5
        if: ${{ success() || failure() }}
        with:
          name: Tax-Service-Unit-Test-Results
          path: "tax/**/*-reports/TEST*.xml"
          reporter: java-junit
      - name: Add coverage report to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{github.workspace}}/tax/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          title: 'Tax Coverage Report'
          update-comment: true

  Build:
    needs: Test
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven Build Command
        run: mvn clean package -DskipTests -pl tax -am
      # - name: Log in to the Container registry
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build Docker image
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./tax
      #     push: false
      #     load: true
      #     tags: ghcr.io/nashtech-garage/yas-tax:latest
      # - name: Snyk - Container Scan
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: snyk/actions/docker@9adf32b1121593767fc3c057af55b55db032dc04
      #   continue-on-error: true
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     image: ghcr.io/nashtech-garage/yas-tax:latest
      #     args: --severity-threshold=high
      # - name: Push Docker image
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   run: docker push ghcr.io/nashtech-garage/yas-tax:latest
